import Link from 'next/link';
import React from 'react';

export const metadata = {
    title: "About Us Page",
    description: "Generated by create next app",
};
const page = () => {


    return (
        <div>
            <h1>This is the about us page</h1>
        </div>
    );
};

export default page;